version: '3.7'
services:
  nginx:
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend
  backend:
    build: backend
    working_dir: /app
    command: python3 ./app/main.py
    ports:
      - 8888:8888
    tty: true
    environment:
      PYTHONPATH: .
      DATABASE_URL: '${POSTGRES_URL}'
      HASH_KEY: "${HASH_KEY}"
      S3_BUCKET_NAME: '${S3_BUCKET_NAME}'
      S3_KEY_INTERNAL: '${S3_KEY_INTERNAL}'
      S3_SECRET_INTERNAL: '${S3_SECRET_INTERNAL}'
      GOOGLE_APPLICATION_CREDENTIALS: '${GOOGLE_APPLICATION_CREDENTIALS}'
      GOOGLE_CLOUD_PROJECT_ID: '${GOOGLE_CLOUD_PROJECT_ID}'
      GOOGLE_CLOUD_PROCESSOR_ID: '${GOOGLE_CLOUD_PROCESSOR_ID}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8888/api"]
      interval: 15s
      timeout: 30s
      retries: 5
  # frontend:
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   stdin_open: true


